### ISSUE TITLE
Edits to English language on Homepage

### ISSUE THREAD

**Issue by Gemmamysoc** [ocftw/civictechfest.org#36]
**Homepage:**

1. 'Ticket' on top menu bar should be 'Tickets'

2. 'Asia’s First Ever Civic Technology Festival with a week-long Collection of Events.' should be: 'Asia’s first ever Civic Technology Festival with a week-long collection of events.'

3. 'TICTeC alongside with WCIT': delete 'with' 

4. Replace the text under 'TICTeC @ Taipei' with:

Civic Tech Fest's main event is “TICTeC@Taipei: The Impacts of Civic Technology Conference”, co-organized by UK group “mySociety”. Started in 2015, TICTeC is the civic tech sector's annual research conference that focuses on the impacts of civic technology projects. This is the first time the conference has been held in Asia, making it a great opportunity to connect global civic tech actors from across the world. 

5. Replace 'Get Ticket !' with: 'Register Now' 

6. Replace the text under 'About WCIT 2017' with:

The 21st World Congress on Information Technology (WCIT 2017) is the parallel event of #CivicTechFest. It will be held at the same time and at the same location as TICTeC@Taipei and will be a really unique opportunity to showcase open government and civic tech initiatives to the wider IT industry.

7. Replace the text under 'Civic Tech Grant DEMO Party' with:

The first g0v Civic Tech Grant awardees will demonstrate their prototypes after 6 months of development. Join the party!

8. Under 'g0v Hackathon' the sentence 'Don’t ask why “nobody” is doing this, you are the “nobody”!' doesn't make too much sense in English :) You may want to reword it.  Something like this for example: 'If you think a tool should exist, then come and hack on it!'

**Comment by ttcat** [comment]
@pellaeon please fix 1 (not only the menu, also the page title)
2~7 fixed

let me ask @clkao to revise 8

**Comment by pellaeon** [comment]
Fixed 1

**Comment by ttcat** [comment]
@Gemmamysoc about 8, how about change "nobody" to no one?

don’t ask why no one is doing it – you are that “no one”! cc @clkao

**Comment by Gemmamysoc** [comment]
@ttcat. No, that still doesn't work, it just sounds confusing. How about:

'If you're asking yourself why nobody is doing it, why not be that nobody and do it yourself!'

or 

'If nobody's doing it yet, all it takes is a somebody to get the project started'
